### ISSUE TITLE
Feature Request: Ability to dork user's repositories

### ISSUE THREAD

**Issue by ajmeese7** [mxrch/GitFive#18]
One feature that I would *really* like to see added to this tool is the ability to dork user's repositories:

![Dorking sheet](https://user-images.githubusercontent.com/17814535/204949404-61e0c0a9-aa87-41d9-a5d9-40e2c7f870c7.png)

This is useful for hunting threat actors who may have made mistakes during their tool development that leaked some of their API keys, which would allow threat hunters to coordinate with the relevant companies to determine the TA's true identity (or at least additional selectors to pivot off of). This can be done with SSH and FTP as well ([source](https://twitter.com/_nynan/status/1597228825540055040?s=20&t=0JTI_MpsvOQ35LJ-KJizzQ)).

**Comment by mxrch** [comment]
Hi,
That was a feature I wanted in GitFive at the beginning, but : 
1. First solution would be to git clone every repo, but with every commits, and it can takes a lot of time. Some projects already does this well (gitleaks) but it's in Golang (for speed) and it would be dirty to add an external binary that would be called with a system call.
2. We can use dorks. But I think GitHub search only search among the last commits of repos, not all, so it would not be so much interesting, since GitHub now notify the user if he pushed a secret / token / key / whatever.

So I don't think it would be very interesting to implement. ^^

**Comment by ajmeese7** [comment]
I didn't know about gitleaks, thanks for the info! I'll close this out now, IMO it would be worth mentioning this in the project README for other users who may be interested in this feature. Cheers!
