### ISSUE TITLE
Deleted/Suspended Accounts

### ISSUE THREAD

**Issue by ajmeese7** [mxrch/GitFive#2]
Hey @mxrch, this project is great and I'm excited to use it when I get a chance!

I was wondering if you have / are planning to implement some method of support for deleted or suspended accounts. For example, I do OSINT research on malware developers whose accounts are frequently changed whenever their projects are deemed malicious and taken down from GitHub. If there is a way to either archive this deleted data that would be great, although I doubt that's feasible due to the massive amounts of storage it would require.

Ideally if there was a way to alert upon search that there is some reference to the account, i.e. forks that still exist even though the user's repositories have been taken down, so the searcher could identify that the account previously existed, that would be very beneficial to my work. Just food for thought for my personal use case, cheers!

**Comment by mxrch** [comment]
Hi ! Thanks for the kind words !

There are actually no ways to recover data deleted by GitHub, so it might be complexe.

Concerning searching in forks related to a deleted account, one way to do this is searching in the WayBack Machine, joyk, giters, pythonissues, libreddit, teddit, opensourceagenda, githubmemory and all these sites indexing GitHub contents.
If you can retrieve repositories names, check for forks in GitHub Search.

Because actually, I search commits by querying https://api.github.com/search/commits?q=author:mxrch, but GitHub first checks if the username you're searching for is corresponding to a GitHub account, and you can't specify an older username or whatever, it needs to be an existing account.

Cheers !

**Comment by mxrch** [comment]
https://gist.github.com/rjeczalik/81ff08b59d7841970fca82ca39f40a10

If there are a lot of requests for this or if it happens a lot, I would be thinking about automating it ! :)
